/**
 * INFORMATION_ACTIONS represents the actions that are interpreted by the information reducers.
 */
export enum INFORMATION_ACTIONS {
	FETCH_COUNTS_REQUEST = "FETCH_COUNTS_REQUEST",
	FETCH_RECORDS_REQUEST = "FETCH_RECORDS_REQUEST",
	FETCH_RECORDS_SUCCESS = "FETCH_RECORDS_SUCCESS",
}
